@startuml Bank
title Domain Model
BankAccount -> BankAccount: deposit(amount@Num, date@Date)
BankAccount <-- BankAccount: Deposited amount@Num on date@Date
BankAccount -> BankAccount: withdraw(amount@Num, date@Date)
BankAccount <-- BankAccount: Withdrawn amount@Num on date@Date

BankAccount -> Transaction: createTransaction([])
Transaction --> BankAccount: transaction@Transaction



@enduml